#!/usr/bin/env python3
"""V28D Qwen subtitle extractor.

Read the subtitle-change frame list generated by V2.8C, send each existing
change-frame image to Qwen3-VL, and build a de-duplicated bilingual subtitle
JSON/CSV timeline. This script intentionally does not extract frames; it only
uses image paths that are already present in the V2.8C changes file.
"""

from __future__ import annotations

import argparse
import base64
import csv
import json
import mimetypes
import re
import string
import sys
import time as time_module
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any


DEFAULT_CHANGES = Path("output_text/v28c_subtitle_changes.json")
DEFAULT_RAW_JSON = Path("output_text/v28d_qwen_raw_results.json")
DEFAULT_RAW_CSV = Path("output_text/v28d_qwen_raw_results.csv")
DEFAULT_OUT_JSON = Path("output_text/v28d_bilingual_subtitles.json")
DEFAULT_OUT_CSV = Path("output_text/v28d_bilingual_subtitles.csv")
DEFAULT_MODEL = "qwen3-vl-plus"
DEFAULT_API_KEY_FILE = Path("qwen_api_key.txt")
QWEN_COMPATIBLE_ENDPOINT = (
    "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
)
REQUEST_TIMEOUT_SECONDS = 90
RETRY_COUNT = 2

SYSTEM_PROMPT = """你是一个严格的影视字幕 OCR 提取器。你只能返回 JSON，不要返回 Markdown、解释或代码块。"""

USER_PROMPT = """只读取画面底部的中英文对白字幕，并返回严格 JSON：
{
  "zh": "...",
  "en": "..."
}

规则：
- 只读取画面底部的中英文对白字幕。
- 不读取演员名。
- 不读取 starring。
- 不读取 Season / Episode。
- 不读取片头歌词。
- 不读取 B站播放器 UI。
- 不读取右上角水印。
- 不读取审查号。
- 如果画面底部没有中英文对白字幕，或文字不是对白字幕，返回 {"zh":"","en":""}。
- 如果只有中文或只有英文，缺失的一项返回空字符串。
- 只允许返回 JSON 对象，不要添加任何额外文本。"""


@dataclass
class ChangeFrame:
    time: float
    image: str


@dataclass
class RawResult:
    time: float
    image: str
    zh: str = ""
    en: str = ""
    error: str = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read V2.8C subtitle-change frames, call Qwen3-VL for burned-in "
            "bilingual subtitles, and write raw plus de-duplicated results."
        )
    )
    parser.add_argument(
        "--changes",
        default=str(DEFAULT_CHANGES),
        help=f"Input V2.8C changes JSON (default: {DEFAULT_CHANGES})",
    )
    parser.add_argument(
        "--raw-json",
        default=str(DEFAULT_RAW_JSON),
        help=f"Raw Qwen result JSON output (default: {DEFAULT_RAW_JSON})",
    )
    parser.add_argument(
        "--raw-csv",
        default=str(DEFAULT_RAW_CSV),
        help=f"Raw Qwen result CSV output (default: {DEFAULT_RAW_CSV})",
    )
    parser.add_argument(
        "--out-json",
        default=str(DEFAULT_OUT_JSON),
        help=f"De-duplicated subtitle JSON output (default: {DEFAULT_OUT_JSON})",
    )
    parser.add_argument(
        "--out-csv",
        default=str(DEFAULT_OUT_CSV),
        help=f"De-duplicated subtitle CSV output (default: {DEFAULT_OUT_CSV})",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"Qwen VL model name (default: {DEFAULT_MODEL})",
    )
    return parser.parse_args()


def normalize_text(text: Any) -> str:
    if text is None:
        return ""
    text = str(text).replace("\u3000", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def normalize_for_similarity(text: str) -> str:
    text = normalize_text(text).casefold()
    punctuation = string.punctuation + "，。！？、；：‘’“”（）【】《》〈〉—…·￥～「」『』〔〕［］｛｝"
    punctuation_pattern = "[" + re.escape(punctuation) + r"\s]+"
    return re.sub(punctuation_pattern, "", text)


def to_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def first_present(mapping: dict[str, Any], keys: tuple[str, ...]) -> Any:
    for key in keys:
        if key in mapping:
            return mapping[key]
    return None


def find_change_items(payload: Any) -> list[Any]:
    """Find the list containing V2.8C change-frame records."""
    if isinstance(payload, list):
        return payload

    if not isinstance(payload, dict):
        raise ValueError("Changes JSON must be a list or object containing a list")

    preferred_keys = (
        "changes",
        "subtitle_changes",
        "subtitleChanges",
        "change_frames",
        "changeFrames",
        "frames",
        "samples",
        "results",
        "data",
    )
    for key in preferred_keys:
        value = payload.get(key)
        if isinstance(value, list):
            return value

    for value in payload.values():
        if isinstance(value, list) and any(
            isinstance(item, dict) and "image" in item for item in value
        ):
            return value

    raise ValueError("Unable to find a change-frame list with image paths")


def load_changes(path: Path) -> list[ChangeFrame]:
    with path.open("r", encoding="utf-8") as json_file:
        payload = json.load(json_file)

    base_dir = path.parent
    changes: list[ChangeFrame] = []
    for index, item in enumerate(find_change_items(payload)):
        if not isinstance(item, dict):
            continue

        image = first_present(item, ("image", "image_path", "imagePath", "path", "frame"))
        if not image:
            continue

        time_value = first_present(
            item,
            (
                "time",
                "timestamp",
                "seconds",
                "sec",
                "start",
                "start_time",
                "startTime",
                "t",
            ),
        )
        if time_value is None:
            time_value = index

        image_path = Path(str(image))
        if not image_path.is_absolute() and not image_path.exists():
            candidate = base_dir / image_path
            if candidate.exists():
                image_path = candidate

        changes.append(ChangeFrame(time=round(to_float(time_value), 3), image=str(image_path)))

    if not changes:
        raise ValueError(f"No usable change-frame records found in {path}")

    return sorted(changes, key=lambda frame: frame.time)


def load_api_key(path: Path = DEFAULT_API_KEY_FILE) -> str:
    if not path.exists():
        raise FileNotFoundError(f"Qwen API key file not found: {path}")
    api_key = path.read_text(encoding="utf-8").strip()
    if not api_key:
        raise ValueError(f"Qwen API key file is empty: {path}")
    return api_key


def image_to_data_url(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"Image not found: {path}")
    mime_type = mimetypes.guess_type(str(path))[0] or "image/jpeg"
    image_bytes = path.read_bytes()
    encoded = base64.b64encode(image_bytes).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def extract_json_object(text: str) -> dict[str, Any]:
    clean_text = text.strip()
    if clean_text.startswith("```"):
        clean_text = re.sub(r"^```(?:json)?\s*", "", clean_text, flags=re.IGNORECASE)
        clean_text = re.sub(r"\s*```$", "", clean_text)

    try:
        parsed = json.loads(clean_text)
    except json.JSONDecodeError:
        start = clean_text.find("{")
        end = clean_text.rfind("}")
        if start < 0 or end <= start:
            raise
        parsed = json.loads(clean_text[start : end + 1])

    if not isinstance(parsed, dict):
        raise ValueError("Model response JSON is not an object")
    return parsed


def parse_qwen_response(payload: dict[str, Any]) -> tuple[str, str]:
    choices = payload.get("choices")
    if not isinstance(choices, list) or not choices:
        raise ValueError("Qwen response does not contain choices")

    message = choices[0].get("message") if isinstance(choices[0], dict) else None
    if not isinstance(message, dict):
        raise ValueError("Qwen response choice does not contain a message")

    content = message.get("content", "")
    if isinstance(content, list):
        content_text = "".join(
            part.get("text", "")
            for part in content
            if isinstance(part, dict) and isinstance(part.get("text", ""), str)
        )
    else:
        content_text = str(content)

    result = extract_json_object(content_text)
    return normalize_text(result.get("zh", "")), normalize_text(result.get("en", ""))


def call_qwen(image_path: Path, api_key: str, model: str) -> tuple[str, str]:
    data_url = image_to_data_url(image_path)
    request_payload = {
        "model": model,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": [
                    {"type": "image_url", "image_url": {"url": data_url}},
                    {"type": "text", "text": USER_PROMPT},
                ],
            },
        ],
    }
    request_body = json.dumps(request_payload, ensure_ascii=False).encode("utf-8")
    request = urllib.request.Request(
        QWEN_COMPATIBLE_ENDPOINT,
        data=request_body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT_SECONDS) as response:
        response_payload = json.loads(response.read().decode("utf-8"))
    return parse_qwen_response(response_payload)


def call_qwen_with_retries(image_path: Path, api_key: str, model: str) -> tuple[str, str]:
    last_error: Exception | None = None
    for attempt in range(RETRY_COUNT + 1):
        try:
            return call_qwen(image_path, api_key, model)
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            last_error = RuntimeError(f"HTTP {exc.code}: {detail}")
        except Exception as exc:  # Keep one bad frame from stopping the batch.
            last_error = exc

        if attempt < RETRY_COUNT:
            time_module.sleep(1.5 * (attempt + 1))

    raise RuntimeError(str(last_error) if last_error else "Unknown Qwen request error")


def process_changes(changes: list[ChangeFrame], api_key: str, model: str) -> list[RawResult]:
    results: list[RawResult] = []
    total = len(changes)

    for index, change in enumerate(changes, start=1):
        print(
            f"[{index}/{total}] {change.time:.2f}s | {change.image}",
            flush=True,
        )
        raw = RawResult(time=change.time, image=change.image)
        try:
            raw.zh, raw.en = call_qwen_with_retries(Path(change.image), api_key, model)
            print(f"    zh={raw.zh!r} | en={raw.en!r}", flush=True)
        except Exception as exc:  # Per-frame failures are captured in raw output.
            raw.error = str(exc)
            print(f"    ERROR: {raw.error}", file=sys.stderr, flush=True)
        results.append(raw)

    return results


def raw_result_to_dict(result: RawResult) -> dict[str, Any]:
    return {
        "time": round(result.time, 3),
        "image": result.image,
        "zh": result.zh,
        "en": result.en,
        "error": result.error,
    }


def write_raw_json(path: Path, results: list[RawResult]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as json_file:
        json.dump([raw_result_to_dict(result) for result in results], json_file, ensure_ascii=False, indent=2)
        json_file.write("\n")


def write_raw_csv(path: Path, results: list[RawResult]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=["time", "image", "zh", "en", "error"])
        writer.writeheader()
        for result in results:
            writer.writerow(raw_result_to_dict(result))


def is_duplicate(current: tuple[str, str], previous: tuple[str, str] | None) -> bool:
    if previous is None:
        return False
    if current == previous:
        return True

    current_normalized = (
        normalize_for_similarity(current[0]),
        normalize_for_similarity(current[1]),
    )
    previous_normalized = (
        normalize_for_similarity(previous[0]),
        normalize_for_similarity(previous[1]),
    )
    return current_normalized == previous_normalized


def build_bilingual_subtitles(results: list[RawResult]) -> list[dict[str, Any]]:
    compact: list[dict[str, Any]] = []
    previous_text: tuple[str, str] | None = None

    for result in sorted(results, key=lambda item: item.time):
        zh = normalize_text(result.zh)
        en = normalize_text(result.en)
        if not zh and not en:
            continue

        current_text = (zh, en)
        if is_duplicate(current_text, previous_text):
            continue

        compact.append(
            {
                "start": round(result.time, 2),
                "end": 0.0,
                "zh": zh,
                "en": en,
            }
        )
        previous_text = current_text

    for index, subtitle in enumerate(compact):
        if index + 1 < len(compact):
            subtitle["end"] = round(float(compact[index + 1]["start"]), 2)
        else:
            subtitle["end"] = round(float(subtitle["start"]) + 2.0, 2)

    return compact


def write_subtitles_json(path: Path, subtitles: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as json_file:
        json.dump(subtitles, json_file, ensure_ascii=False, indent=2)
        json_file.write("\n")


def write_subtitles_csv(path: Path, subtitles: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=["start", "end", "zh", "en"])
        writer.writeheader()
        for subtitle in subtitles:
            writer.writerow(subtitle)


def main() -> int:
    args = parse_args()
    changes_path = Path(args.changes)

    try:
        changes = load_changes(changes_path)
        api_key = load_api_key()
        raw_results = process_changes(changes, api_key, args.model)
        subtitles = build_bilingual_subtitles(raw_results)

        write_raw_json(Path(args.raw_json), raw_results)
        write_raw_csv(Path(args.raw_csv), raw_results)
        write_subtitles_json(Path(args.out_json), subtitles)
        write_subtitles_csv(Path(args.out_csv), subtitles)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote raw JSON: {args.raw_json}")
    print(f"Wrote raw CSV: {args.raw_csv}")
    print(f"Wrote subtitles JSON: {args.out_json}")
    print(f"Wrote subtitles CSV: {args.out_csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
